### ISSUE TITLE
Implement Mongoose for database?

### ISSUE THREAD

**Issue by elementzprojects** [elementzprojects/tensorbotdiscord#6]

**Comment by generic-github-user** [comment]
I am currently trying to implement [Firebase](https://firebase.google.com/). It may be difficult to do so with Heroku, however, because it requires an entire authentication file as opposed to a single variable. Native integration from Firebase to Heroku or vice versa may be possible.

**Comment by generic-github-user** [comment]
[Firebase Realtime Database](https://firebase.google.com/docs/database/) has been set up and is working fine. I am closing this issue for now.
