### ISSUE TITLE
Error: Failed to parse private key: Error: Invalid PEM formatted message when loading environment variable from Heroku

### ISSUE THREAD

**Issue by generic-github-user** [elementzprojects/tensorbotdiscord#8]

**Comment by generic-github-user** [comment]
This indicates that the private key needed to authenticate with a Firebase realtime database is incorrectly formatted. I initially assumed this was due to the numerous `\n` characters placed sporadically throughout the private key. As a result, it seemed necessary to sanitize the private key after it is retrieved as a Heroku environment variable. I did so in the manner described in [this answer](https://stackoverflow.com/questions/39492587/escaping-issue-with-firebase-privatekey-as-a-heroku-config-variable/41044630#41044630). However, this did not resolve the issue.

**Comment by generic-github-user** [comment]
Since the variable sanitizing solution did not work, I also tried [this solution](https://stackoverflow.com/a/44396402/10940584), which involves adding quotes around the stored variable and using [`JSON.parse()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse) to convert it to a valid string. The same error was still logged.

**Comment by generic-github-user** [comment]
I also tried using `escape()` and `unescape()` instead of a regular expression to sanitize the input, as well as checking that the stored private key variable was formatted on one line in Heroku. The error remained.

**Comment by generic-github-user** [comment]
In the end, it turned out that the header and footer of the private key string was not stored in Heroku along with the content of the key. Oh well.

![image](https://user-images.githubusercontent.com/40661852/52244957-aab5b880-28ad-11e9-8a1d-876453e5c84b.png)
![image](https://user-images.githubusercontent.com/40661852/52244963-b0ab9980-28ad-11e9-9313-03a15aab0cac.png)

**Comment by elementzprojects** [comment]
Very silly of me forgetting the header and footer haha
